const demoUsers = [
  {
    firstName: 'Liam',
    lastName: 'Shelton',
    email: 'lshelton0@gmail.com',
    password: 'BJB6qr7fdsfsd4ee4',
    age: 25,
    gender: 'M',
    address1: '2 Crest Line Pass',
    address2: null,
    city: 'Bronx',
    state: 'NY',
    lastLat: 34.0522,
    lastLong: -118.2437,
    zip: 10451,
    avatarUrl: '/assets/demoUserImg/M1.jpg',
    aboutMe:
      'As a journalist, I spend my days writing and researching stories. But when I am off, you can find me at the beach, practicing yoga, or trying out new restaurants in town.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Leticia',
    lastName: 'Linscott',
    email: 'llinscott1@gmail.com',
    password: 'VtBW9r43wf4e453L',
    age: 23,
    gender: 'F',
    address1: '35359 Forest Crossing',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F16.jpg',
    aboutMe:
      'I am a UX designer who loves to paint, take photos, and spend time with my family and friends on the weekends.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Emma',
    lastName: 'Padmore',
    email: 'epadmore2@gmail.com',
    password: 'SpXEMQm4533454rff4',
    age: 30,
    gender: 'F',
    address1: '928 Maryland Drive',
    address2: 'Suite 79',
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F5.jpg',
    aboutMe:
      'I am a teacher who loves to spend my free time reading, writing, and practicing mindfulness.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Oliver',
    lastName: 'Reddyhoff',
    email: 'dreddyhoff3@gmail.com',
    password: '3ukaWNfefer4534543j',
    age: 34,
    gender: 'M',
    address1: '60 Loftsgordon Terrace',
    address2: null,
    city: 'Bronx',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10451,
    avatarUrl: '/assets/demoUserImg/M2.jpg',
    aboutMe:
      'Hey, my name is Oliver and I am a web developer who loves to ride my bike, play guitar, and experiment with new recipes in the kitchen.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Lucas',
    lastName: 'Mickan',
    email: 'gmickan4@gmail.com',
    password: 'cw8O7bFd43r534feeef',
    age: 28,
    gender: 'M',
    address1: '08 Forest Run Junction',
    address2: null,
    city: 'Queens',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11005,
    avatarUrl: '/assets/demoUserImg/M8.jpg',
    aboutMe:
      'My name is Lucas, and I work as a photographer. In my spare time, you can find me hiking, camping, and exploring new places with my camera.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'William',
    lastName: 'Mattocks',
    email: 'smattocks5@gmail.com',
    password: 'WCmrdGfefdsfe454354',
    age: 23,
    gender: 'M',
    address1: '63 Fair Oaks Street',
    address2: null,
    city: 'Queens',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11005,
    avatarUrl: '/assets/demoUserImg/M7.jpg',
    aboutMe:
      'I am a writer by profession and love to spend my free time reading books, traveling, and practicing yoga.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'James',
    lastName: 'Threadgould',
    email: 'lthreadgould6@nationalgeographic.com',
    password: '1mkNyQSSfOSAerdscfser4353',
    age: 32,
    gender: 'M',
    address1: '7968 Mccormick Avenue',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/M9.jpg',
    aboutMe:
      'Hi, my name is James, a social media manager who enjoys hiking with my dog, practicing yoga, and trying out new recipes in the kitchen.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Sophia',
    lastName: 'Derrick',
    email: 'sophiederrick@gmail.com',
    password: 'Kjl8YB43r34r3rfer3',
    age: 34,
    gender: 'F',
    address1: '08693 Hooker Terrace',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F22.jpg',
    aboutMe:
      'As a nurse, I spend my days taking care of others. But when I am off, you can find me at the gym or cooking up a storm in the kitchen.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Aurelea',
    lastName: 'Waything',
    email: 'awaything8@gmail.com',
    password: 'KQhUZKpBzK8c43535r5w34',
    age: 31,
    gender: 'F',
    address1: '20 Northview Court',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/F24.jpg',
    aboutMe:
      'I am a lawyer who loves to unwind with a good game of tennis or a hike in the mountains.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Hana',
    lastName: 'Fairey',
    email: 'hfairey9@google.com',
    password: '5Lo6fmTwP45r3er34fw',
    age: 26,
    gender: 'F',
    address1: '909 Cody Circle',
    address2: 'Room 1713',
    city: 'Queens',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11005,
    avatarUrl: '/assets/demoUserImg/F12.jpg',
    aboutMe:
      'My name is Hana, and I work as a marketer. I am also an avid traveler and enjoy exploring new cultures and cuisines.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Joye',
    lastName: 'Versey',
    email: 'jverseya@gmail.com',
    password: 'OF3oqF9zbqJr43r34rfe435',
    age: 35,
    gender: 'F',
    address1: '5 Farragut Junction',
    address2: 'Suite 23',
    city: 'Staten Island',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10311,
    avatarUrl: '/assets/demoUserImg/F1.jpg',
    aboutMe:
      'As an accountant, numbers are my bread and butter. But when I am not crunching numbers, I like to go camping and fishing with my family.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Derick',
    lastName: 'Twinn',
    email: 'dtwinnb@gmail.com',
    password: 'eFdUBsG43r34fwe34534543',
    age: 30,
    gender: 'M',
    address1: '0 Pawling Point',
    address2: 'Suite 56',
    city: 'Staten Island',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10311,
    avatarUrl: '/assets/demoUserImg/M4.jpg',
    aboutMe:
      'My name is Derick and I work as a scientist. In my free time, I like to go running, watch movies, and tinker with electronics.',
    isVerified: false,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Dallis',
    lastName: 'Starling',
    email: 'dstarlingc@gmail.com',
    password: 'fpFkZv343543fesdrr34',
    age: 32,
    gender: 'M',
    address1: '02282 Towne Trail',
    address2: null,
    city: 'Brooklyn',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 11228,
    avatarUrl: '/assets/demoUserImg/M11.jpg',
    aboutMe:
      'My name is Dallis, and I am a graphic designer who loves to paint and explore new coffee shops in my spare time.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Cathie',
    lastName: 'Meo',
    email: 'cmeod@gmail.com',
    password: 'CvW9Xt6h43r3rrtefsdr435',
    age: 25,
    gender: 'F',
    address1: '28 Lawn Hill',
    address2: null,
    city: 'Bronx',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10451,
    avatarUrl: '/assets/demoUserImg/F25.jpg',
    aboutMe:
      'Hi, I am Cathy, a veterinarian who loves to knit, read books, and travel to new places whenever possible.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
  {
    firstName: 'Kilian',
    lastName: 'Riceards',
    email: 'kriceardse@gmail.com',
    password: 'cUOq62Xb43rw3dfwe',
    age: 34,
    gender: 'M',
    address1: '78975 Mockingbird Street',
    address2: null,
    city: 'Bronx',
    state: 'NY',
    lastLat: null,
    lastLong: null,
    zip: 10451,
    avatarUrl: '/assets/demoUserImg/M6.jpg',
    aboutMe:
      'Hi, I am Killian! I work as a software engineer during the day and enjoy hiking and photography on the weekends.',
    isVerified: true,
    role: 'user',
    status: 'active',
  },
];

module.exports = demoUsers;
