const ratings = [
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment:
      'Influenza due to identified 2009 H1N1 influenza virus with other respiratory manifestations',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment:
      'Closed fractures involving skull or face with other bones, with intracranial injury of other and unspecified nature, with concussion, unspecified',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Contact with or exposure to escherichia coli (E. coli)',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment:
      'Other closed skull fracture without mention of intracranial injury, with no loss of consciousness',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 1,
    reportComment:
      'Full-thickness skin loss [third degree,not otherwise specified] of breast',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment: 'Chronic motor or vocal tic disorder',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment:
      'Other accidental submersion or drowning in water transport accident injuring occupant of other watercraft -- other than crew',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment:
      'Rupture of uterus during labor, delivered, with or without mention of antepartum condition',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Disorders of soft tissue, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 1,
    reportComment:
      'Closed fracture of vault of skull with subarachnoid, subdural, and extradural hemorrhage, with concussion, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 4,
    reportComment: 'Chronic monocytic leukemia, in relapse',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment: 'Disorders of mitochondrial metabolism',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Arteritis, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Methemoglobinemia',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Helminth infection, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Pneumonia due to Staphylococcus, unspecified',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment: 'Open dislocation of radioulnar (joint), distal',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Other corneal deposits associated with metabolic disorders',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Persistent hyperplasia of thymus',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment:
      'Elderly multigravida, delivered with or without mention of antepartum condition',
    isReport: true,
    reportIsUpheld: true,
  },
  {
    rating: 5,
    reportComment:
      'Hypertensive heart and chronic kidney disease, malignant, without heart failure and with chronic kidney disease stage I through stage IV, or unspecified',
    isReport: true,
    reportIsUpheld: true,
  },
  {
    rating: 2,
    reportComment: 'Respiratory conditions due to smoke inhalation',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment:
      'Infections of nipple associated with childbirth, unspecified as to episode of care or not applicable',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 4,
    reportComment:
      'Tuberculous peritonitis, bacteriological or histological examination unknown (at present)',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment:
      'Suspected problem with amniotic cavity and membrane not found',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Hordeolum internum',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Long-term (current) use of steroids',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 3,
    reportComment: 'Septic pulmonary embolism',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Loose body in joint, multiple sites',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Asthma, unspecified type, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment: 'Other anxiety states',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment:
      'Need for prophylactic vaccination and inoculation against streptococcus pneumoniae [pneumococcus] and influenza',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment:
      'Genitourinary tuberculosis, unspecified, tubercle bacilli found (in sputum) by microscopy',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Personal history of malignant neoplasm of kidney',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Secondary neuroendocrine tumor of distant lymph nodes',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Cluster headache syndrome, unspecified',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment:
      'Edema or excessive weight gain in pregnancy, without mention of hypertension, postpartum condition or complication',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Complications of reattached forearm',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment: 'Spontaneous abortion, complicated by embolism, unspecified',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment: 'Unspecified pleural effusion',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment: 'Cubitus valgus (acquired)',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment: 'Activities involving dancing',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Circumpapillary dystrophy of choroid, partial',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 1,
    reportComment:
      'Vaccination not carried out because patient had disease being vaccinated against',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment:
      'Illegally induced abortion, complicated by renal failure, unspecified',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment:
      'Other vascular complications of medical care, not elsewhere classified',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment:
      'Closed fracture of vault of skull with other and unspecified intracranial hemorrhage, with prolonged [more than 24 hours] loss of consciousness and return to pre-existing conscious level',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 4,
    reportComment:
      'Other vomiting complicating pregnancy, antepartum condition or complication',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 5,
    reportComment: 'Scorpion sting causing poisoning and toxic reactions',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment:
      'Bacterial infection, unspecified, in conditions classified elsewhere and of unspecified site',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Personal history of tobacco use',
    isReport: true,
    reportIsUpheld: true,
  },
  {
    rating: 5,
    reportComment: 'Hemarthrosis, pelvic region and thigh',
    isReport: true,
    reportIsUpheld: true,
  },
  {
    rating: 1,
    reportComment:
      'Injury due to war operations by unarmed hand-to-hand combat',
    isReport: true,
    reportIsUpheld: false,
  },
  {
    rating: 5,
    reportComment: 'Multiple myeloma, in relapse',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment:
      'Coronary atherosclerosis of native coronary artery of transplanted heart',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment: 'Poisoning by saluretics',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Flaccid hemiplegia and hemiparesis affecting dominant side',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment: 'Malignant neoplasm of base of tongue',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 3,
    reportComment: 'Urethral diverticulum',
    isReport: true,
    reportIsUpheld: true,
  },
  {
    rating: 4,
    reportComment:
      'Chronic migraine without aura, with intractable migraine, so stated, without mention of status migrainosus',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 5,
    reportComment:
      'Chondrocalcinosis, due to pyrophosphate crystals, shoulder region',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 4,
    reportComment: 'Erysipelas',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment: 'Vomiting following gastrointestinal surgery',
    isReport: true,
    reportIsUpheld: true,
  },
  { rating: 4, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 1,
    reportComment:
      'Injury due to war operations by unintentional destruction of aircraft due to own onboard explosives',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 3, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  {
    rating: 2,
    reportComment: 'Herpes zoster with unspecified complication',
    isReport: true,
    reportIsUpheld: false,
  },
  { rating: 1, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 2, reportComment: null, isReport: false, reportIsUpheld: false },
  { rating: 5, reportComment: null, isReport: false, reportIsUpheld: false },
];

module.exports = ratings;
