module.exports = {
  businesses: [
    {
      id: 'yXg-x80McENKhH52Na6DqQ',
      alias: 'grab-a-gyro-tualatin-4',
      name: 'Grab A Gyro',
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/Xi1egWsFfu6TH12q9QQUEA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/grab-a-gyro-tualatin-4?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 136,
      categories: [Array],
      rating: 4.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15034540510',
      display_phone: '(503) 454-0510',
      distance: 1101.9716441042135,
    },
    {
      id: '9gTV68oIVRyZjz07bACx6w',
      alias: '808-grinds-portland-7',
      name: '808 Grinds',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/Vriyb-8FXxxAO5tTPLS-Qg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/808-grinds-portland-7?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 220,
      categories: [Array],
      rating: 4.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$',
      location: [Object],
      phone: '+15034779976',
      display_phone: '(503) 477-9976',
      distance: 15021.899948326836,
    },
    {
      id: 'pG-PyLwPzwzC46Trup8icA',
      alias: 'rocket-breakfast-portland',
      name: 'Rocket Breakfast',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/3ieXFA2ff_mF7dYtBpH_JA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/rocket-breakfast-portland?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 112,
      categories: [Array],
      rating: 4.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15036769056',
      display_phone: '(503) 676-9056',
      distance: 22159.119755662992,
    },
    {
      id: 'wjW3sJiRiKVgmiaa-yUEUA',
      alias: 'nothing-bundt-cakes-tualatin-2',
      name: 'Nothing Bundt Cakes',
      image_url:
        'https://s3-media4.fl.yelpcdn.com/bphoto/SfHTVTQVbBMFuUSpfHi6ig/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/nothing-bundt-cakes-tualatin-2?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 89,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15034865193',
      display_phone: '(503) 486-5193',
      distance: 873.3600913209186,
    },
    {
      id: 'qIiRyyR9vk9LffiTrMDXwQ',
      alias: 'taqueria-las-casitas-tualatin',
      name: 'Taqueria Las  Casitas',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/6Df0pf32sSI4xbGPa_trgA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/taqueria-las-casitas-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 123,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [],
      price: '$',
      location: [Object],
      phone: '+15035635088',
      display_phone: '(503) 563-5088',
      distance: 840.863473962304,
    },
    {
      id: 'EbGDXPN8QFbUoA_sabnH8Q',
      alias: 'sunnys-diner-nyberg-tualatin',
      name: "Sunny's Diner Nyberg",
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/FWeCKIOdT7SquVt8RVC0MA/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/sunnys-diner-nyberg-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 34,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      location: [Object],
      phone: '+15036589988',
      display_phone: '(503) 658-9988',
      distance: 1680.724632525632,
    },
    {
      id: 'LSIYTOJNfgBdIVk0RspLlQ',
      alias: 'g-man-sports-bar-tualatin-3',
      name: 'G-Man Sports Bar',
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/Btal1zw-UlQjY_imS7r5YQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/g-man-sports-bar-tualatin-3?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 199,
      categories: [Array],
      rating: 3.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15038858787',
      display_phone: '(503) 885-8787',
      distance: 1307.3837646593636,
    },
    {
      id: 'rbuj2X4SXIc3MDul4dcxIA',
      alias: 'puddletown-bagels-bakery-and-cafe-portland',
      name: 'Puddletown Bagels - Bakery & Cafe',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/9EszqGWeccSSi3rNEzxelg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/puddletown-bagels-bakery-and-cafe-portland?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 111,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$',
      location: [Object],
      phone: '+15034900894',
      display_phone: '(503) 490-0894',
      distance: 17779.285639149195,
    },
    {
      id: 'a7oLsH8qSTVOdTku84Q75A',
      alias: 'charlies-deli-and-delivery-portland',
      name: "Charlie's Deli & Delivery",
      image_url:
        'https://s3-media4.fl.yelpcdn.com/bphoto/94m5gXQIVeFqZqqgP1CzKQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/charlies-deli-and-delivery-portland?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 321,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15039029428',
      display_phone: '(503) 902-9428',
      distance: 18128.68561593777,
    },
    {
      id: 'egZDNQ-dsuALqssroaPRQA',
      alias: 'the-ci-bar-and-grill-tualatin',
      name: 'The CI Bar and Grill',
      image_url:
        'https://s3-media4.fl.yelpcdn.com/bphoto/b6QW3Jsv_SrfOgeP99GafQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-ci-bar-and-grill-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 66,
      categories: [Array],
      rating: 3.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15036922765',
      display_phone: '(503) 692-2765',
      distance: 1306.0473413756313,
    },
    {
      id: 'W0Bkxyn4EMCar7cN11bQ2g',
      alias: 'habaneros-mexican-food-tualatin-2',
      name: 'Habaneros Mexican Food',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/KGRc41lWX-D3m18HSIRCEw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/habaneros-mexican-food-tualatin-2?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 117,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      location: [Object],
      phone: '+15034272779',
      display_phone: '(503) 427-2779',
      distance: 948.7893226932222,
    },
    {
      id: 'K_xU_7ndVvVKO5zM7shWLA',
      alias: 'el-ranchito-alegre-tualatin-4',
      name: 'El Ranchito Alegre',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/msRgd_RwC_Ozx_2hOhe2tQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/el-ranchito-alegre-tualatin-4?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 20,
      categories: [Array],
      rating: 4.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$',
      location: [Object],
      phone: '+15034825881',
      display_phone: '(503) 482-5881',
      distance: 900.2800492998513,
    },
    {
      id: 'oTFcYvztPWqGlC3JrCTACg',
      alias: 'donut-land-tualatin',
      name: 'Donut Land',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/FGw0aDlCKwcc7ZPw7T8nCg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/donut-land-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 181,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$',
      location: [Object],
      phone: '+15038858641',
      display_phone: '(503) 885-8641',
      distance: 839.0384111447794,
    },
    {
      id: 'b8qGJwkgc6TVEexPW_24Dw',
      alias: 'joy-teriyaki-and-poke-tualatin',
      name: 'Joy Teriyaki & Poke',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/CLwcKaZgTc7RcCs7pHGA1A/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/joy-teriyaki-and-poke-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 69,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15038851943',
      display_phone: '(503) 885-1943',
      distance: 1552.5237639915113,
    },
    {
      id: 'M1a39-Pt7d3uvnaswqlPcw',
      alias: 'vitality-bowls-tualatin',
      name: 'Vitality Bowls',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/2Zm0HUYhDJ7a8MFgptD2rQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/vitality-bowls-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 125,
      categories: [Array],
      rating: 3.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15034825960',
      display_phone: '(503) 482-5960',
      distance: 1226.2044949660453,
    },
    {
      id: 'PcwGSC3W8jOGGWoRqGNXeA',
      alias: 'starbucks-tualatin-10',
      name: 'Starbucks',
      image_url:
        'https://s3-media4.fl.yelpcdn.com/bphoto/vurGfcQ06rQveb6HlTpTbg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/starbucks-tualatin-10?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 22,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15036919448',
      display_phone: '(503) 691-9448',
      distance: 1258.9500956782695,
    },
    {
      id: 'NpXMaWjHNHUiz-F4k0AXgQ',
      alias: 'the-community-at-marquis-tualatin-tualatin',
      name: 'The Community at Marquis Tualatin',
      image_url:
        'https://s3-media1.fl.yelpcdn.com/bphoto/VipetV0Fs8gzB5RLWjR5Zg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/the-community-at-marquis-tualatin-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 4,
      categories: [Array],
      rating: 5,
      coordinates: [Object],
      transactions: [],
      location: [Object],
      phone: '+15036122550',
      display_phone: '(503) 612-2550',
      distance: 623.308763575851,
    },
    {
      id: 'qvmRo-YmPPwecKuesQlEkQ',
      alias: 'dutch-bros-coffee-tualatin',
      name: 'Dutch Bros Coffee',
      image_url:
        'https://s3-media4.fl.yelpcdn.com/bphoto/-0xQ7zGyZR2DUI8rd2zSlw/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/dutch-bros-coffee-tualatin?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 112,
      categories: [Array],
      rating: 3.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$',
      location: [Object],
      phone: '+15419554700',
      display_phone: '(541) 955-4700',
      distance: 1025.9873971466468,
    },
    {
      id: '1-5_B2A0UeS3_OHxYwC5bA',
      alias: 'sharis-cafe-and-pies-tualatin-2',
      name: "Shari's Cafe and Pies",
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/YtSxAMLvU3slNWAY3NpK4w/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/sharis-cafe-and-pies-tualatin-2?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 87,
      categories: [Array],
      rating: 2.5,
      coordinates: [Object],
      transactions: [Array],
      price: '$$',
      location: [Object],
      phone: '+15036921589',
      display_phone: '(503) 692-1589',
      distance: 842.0897139110343,
    },
    {
      id: 'BPBLkLXLmtzhOhWUafK0NA',
      alias: 'cousins-maine-lobster-portland-or-portland',
      name: 'Cousins Maine Lobster - Portland, OR',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/mFX73yq9FvvFxKtupwfmGQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/cousins-maine-lobster-portland-or-portland?adjust_creative=i1IO2ooPncBXEQtxOkfSEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i1IO2ooPncBXEQtxOkfSEw',
      review_count: 27,
      categories: [Array],
      rating: 4,
      coordinates: [Object],
      transactions: [],
      price: '$$',
      location: [Object],
      phone: '+19713571671',
      display_phone: '(971) 357-1671',
      distance: 20941.972985758763,
    },
  ],
  total: 46,
  region: { center: { longitude: -122.7619798, latitude: 45.3724338 } },
};
